# In Backend/model/user.py
# Add DATE to your sqlalchemy imports
from sqlalchemy import Column, String, Text, Boolean, TIMESTAMP, ARRAY, SmallInteger, DATE
from sqlalchemy.dialects.postgresql import UUID, JSONB
from DB.base import Base
import uuid
from sqlalchemy.orm import relationship

class User(Base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email = Column(String(255), unique=True, nullable=False, index=True)
    password = Column(String(255), nullable=False)
    name = Column(String(100), nullable=True)
    university_reg_no = Column(String(50), unique=True, nullable=True)
    biography = Column(Text, nullable=True)
    
    # ... interest columns ...
    interest1 = Column(String(50), nullable=True)
    interest1_weight = Column(SmallInteger, nullable=True)
    interest2 = Column(String(50), nullable=True)
    interest2_weight = Column(SmallInteger, nullable=True)
    interest3 = Column(String(50), nullable=True)
    interest3_weight = Column(SmallInteger, nullable=True)

    # This is your full match pool, generated by the algorithm
    matched_profiles = Column(ARRAY(UUID(as_uuid=True)), default=[])

    is_admin = Column(Boolean, default=False)

    # --- NEW/CONFIRMED COLUMNS ---
    # This is the new column you added for push notifications
    fcm_token = Column(String(255), nullable=True) 
    
    # This stores the static list of 10 for the day
    daily_matches = Column(ARRAY(UUID(as_uuid=True)), default=[])
    
    # This tracks when the daily_matches list was generated
    matches_generated_at = Column(DATE, nullable=True)
    # --- END OF NEW/CONFIRMED COLUMNS ---

    # Relationships to messages
    messages_sent = relationship("Message", foreign_keys="[Message.sender_id]", back_populates="sender")
    messages_received = relationship("Message", foreign_keys="[Message.receiver_id]", back_populates="receiver")
